spring:
  application:
    name: turbine-server

server:
  port: 8769

turbine:
  aggregator:
    cluster-config: defalut
  app-config: eureka-hystrix-client, eureka-hystrix-client1
  cluster-name-expression: new String("default")

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"